### ISSUE TITLE
fresh start - based on osmdroid

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.tour#6]
I did not find a way out of the limitation imposed by the web client, when telling the coordinates of the user. within a web client, you cannot have GPS precision.  this is a show stopper.

I'm considering moving ghini.tour to [osmdroid](https://github.com/osmdroid/osmdroid), this will solve the GPS precision problem, and will let us use osm tiles, instead of a custom drawing with custom geographic referencing.

### todo
- [x] rewrite the README
  - [x] for the user
  - [x] for the garden manager
- [x] throw away everything we have now
- [x] create a new android studio project, based on some of the samples in osmdroid
  - [x] screen has two sections: the map, the text.
  - [x] we have a database holding gardens and points of interest.
  - [x] gardens and points of interest have coordinates and show on the map.
  - [x] gardens and points of interest have a text
  - [x] selecting an object in the map shows the text in the text section.
  - [ ] points of interest are tied to a garden and only show at zoom 17 or more.
- [x] create some dummy data to show one garden in the app

**Comment by mfrasca** [comment]
I think let's just close this generic issue, and go work in detail
